
# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Runs on pushes and pull requests to the "main" branch
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Runs the Python script
      - name: Run hello.py
        run: python hello.py
